name: Update GeoIP Database

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download GeoLite2 file
        run: |
          mkdir -p db
          curl -L -o db/GeoLite2-Country.mmdb https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-Country.mmdb

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add db/GeoLite2-Country.mmdb
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: auto update GeoLite2-Country.mmdb" && git push)
